exclude: .bumpversion.cfg
repos:
-   repo: local
    hooks:
    -   id: print_statements
        name: Check for print statements
        types: [python]
        entry: 'print\(.*?\)(?!.*# functional)'
        language: pygrep
    -   id: show_statements
        name: Check for show statements
        types: [python]
        entry: '\.show\(.*\)'
        language: pygrep

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--max-line-length, "120", "--extend-exclude=tests/**"]

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        args: [--line-length, "120"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML, types-setuptools]

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
