codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 0%
    patch:
      default:
        threshold: 10%

comment:
  layout: "reach,diff,flags,files,footer"
