create_tables:
  - output_file_name: unioned_survey_responses
    table_name: valid_survey_responses
    column_name_map:
      ons_household_id: ons_household_id
      ordered_household_id: hh_id_fake
      hh_id: hh_id
      participant_id: participant_id
      people_in_household_count: n_participants_corrected
      survey_response_dataset_major_version: dataset
      consent_1_visit: consent_v1
      consent_5_visits: consent_v5
      consent_april_22: consent_to_april_22
      consent_16_visits: consent_v16
      consent_blood_test: consent_blood
      consent_contact_extra_research: consent_future_research
      consent_use_of_surplus_blood_samples: consent_blood_surplus
      consent_blood_samples_if_positive: consent_blood_if_positive
      consent_summary: consent
      consent_finger_prick_a1_a3: consent_to_finger_prick_a1_a3
      consent_extend_study_under_16_b1_b3: consent_to_extend_study_swab
      consent_contact_extra_researchyn: consent_future_researchYN
      consent_use_of_surplus_blood_samplesyn: consent_blood_surplusYN
      consent_blood_samples_if_positiveyn: consent_blood_if_positiveYN
      consent_fingerprick_blood_samples: consent_to_fingerprick_blood
      reconsented_blood: re_consent_blood
      approached_for_blood_samples: approached_for_blood_samples
      study_cohort: cohort
      outward_postcode: outer_postcode
      participant_testing_group: work_type
      visit_id: visit_id
      visit_datetime_string: visit_date_time
      visit_date_string: visit_date
      visit_date_type: visit_date_type
      visit_order: visit_order
      household_visit_status: appointment_status
      improved_visit_date_string: actual_visit_date
      participant_visit_status: visit_status
      visit_type: visit_type
      deferred: deferred
      not_attended_reason: not_attend_reason
      household_fingerprick_status: fingerprick_status_hh
      able_to_take_blood: able_to_take_blood
      no_fingerprick_blood_taken_reason: no_blood_reason_fingerprick
      no_venous_blood_taken_reason: no_blood_reason_venous
      accepted_fingerprick_invite: accepted_fingerprick_invite
      samples_taken_datetime_string: samples_taken_date_time
      samples_taken_date_string: samples_taken_date
      swab_taken: swab_taken
      swab_sample_barcode_raw: swab_barcode_IQ
      swab_sample_barcode: swab_barcode_cleaned
      swab_sample_barcode_edited_flag: flag_barcode_swab
      blood_taken: blood_taken
      blood_sample_barcode_raw: blood_barcode_IQ
      blood_sample_barcode: blood_barcode_cleaned
      blood_sample_barcode_edited_flag: flag_barcode_blood
      sex: sex
      age_at_visit: age_at_visit
      ethnicity: ethnicity
      confirm_received_vouchers: confirm_received_vouchers
      have_landline_number: have_landline_number
      have_mobile_number: have_mobile_number
      participant_survey_status: withdrawn_participant
      withdrawal_type: withdrawn_type
      withdrawal_reason: reason_for_withdrawal
      withdrawal_reason_raw: withdrawal_reason
      date_of_birth_string: dob
      illness_reduces_activity_or_ability: health_conditions_impact
      illness_lasting_over_12_months: health_conditions
      have_ever_smoked_regularly: smoke_ever_regularly
      smoke_cigarettes: smoke_now_cigarettes
      smokes_cigar: smoke_now_cigar
      smokes_pipe: smoke_now_pipe
      smokes_vape_e_cigarettes: smoke_now_vape
      smokes_hookah_shisha_pipes: smoke_now_hookah_shisha
      smokes_nothing_now: smoke_now_nothing
      work_main_job_title: job_title
      work_main_job_role: main_resp
      work_sectors_other: work_sector_other_text
      work_sectors: work_sector
      work_health_care_v1_v2: work_healthcare_v1
      work_health_care_v0: work_healthcare
      work_social_care: work_socialcare
      work_nursing_or_residential_care_home: work_care_nursing_home
      work_direct_contact_patients_clients: work_direct_contact_patients_etc
      work_status_v1_raw: orig_v1_work_status
      work_status_v2_raw: work_status_v2_orig
      work_status_v0: work_status
      work_status_v1: work_status_v1
      work_status_v2: work_status_v2
      work_location: work_location
      work_not_from_home_days_per_week: work_outside_home_days
      work_main_job_changed: main_job_changed
      work_in_additional_paid_employment: additional_paid_employment
      ability_to_socially_distance_at_work_or_school: work_social_distancing
      transport_to_work_or_school: work_travel
      symptoms_last_7_days_any: sympt_now_any
      symptoms_last_7_days_fever: sympt_now_fever
      symptoms_last_7_days_muscle_ache_myalgia: sympt_now_muscle_ache_myalgia
      symptoms_last_7_days_fatigue_weakness: sympt_now_fatigue_weakness
      symptoms_last_7_days_sore_throat: sympt_now_sore_throat
      symptoms_last_7_days_cough: sympt_now_cough
      symptoms_last_7_days_shortness_of_breath: sympt_now_shortness_of_breath
      symptoms_last_7_days_headache: sympt_now_headache
      symptoms_last_7_days_nausea_vomiting: sympt_now_nausea_vomiting
      symptoms_last_7_days_abdominal_pain: sympt_now_abdominal_pain
      symptoms_last_7_days_diarrhoea: sympt_now_diarrhoea
      symptoms_last_7_days_loss_of_appetite: sympt_now_loss_of_appetite_or_e
      symptoms_last_7_days_more_trouble_sleeping: sympt_now_more_trouble_sleeping
      symptoms_last_7_days_noisy_breathing_wheezing: sympt_now_noisy_breathing_wheez
      symptoms_last_7_days_runny_nose_sneezing: sympt_now_runny_nose_sneezing
      symptoms_last_7_days_loss_of_taste: sympt_now_loss_of_taste
      symptoms_last_7_days_loss_of_smell: sympt_now_loss_of_smell
      symptoms_last_7_days_onset_date_string: sympt_now_date
      symptoms_last_7_days_vertigo_dizziness: sympt_now_vertigo_dizziness
      symptoms_last_7_days_difficulty_concentrating: sympt_now_difficulty_concentrate
      symptoms_last_7_days_palpitations: sympt_now_palpitations
      symptoms_last_7_days_memory_loss_or_confusion: sympt_now_memory_loss_confusion
      symptoms_last_7_days_chest_pain: sympt_now_chest_pain
      symptoms_last_7_days_worry_anxiety: sympt_now_worry_anxiety
      symptoms_last_7_days_low_mood_not_enjoying_anything: sympt_now_low_mood_not_enjoying
      think_have_covid_symptoms: think_have_covid_sympt_now
      think_had_covid: covid_think_havehad
      think_had_covid_onset_date_string: covid_date
      think_had_covid_contacted_nhs: covid_nhs_contact
      think_had_covid_admitted_to_hospital: covid_admitted
      think_had_covid_any_symptoms: sympt_covid_any
      symptoms_since_last_visit_fever: sympt_covid_fever
      symptoms_since_last_visit_muscle_ache_myalgia: sympt_covid_muscle_ache_myalgia
      symptoms_since_last_visit_fatigue_weakness: sympt_covid_fatigue_weakness
      symptoms_since_last_visit_sore_throat: sympt_covid_sore_throat
      symptoms_since_last_visit_cough: sympt_covid_cough
      symptoms_since_last_visit_shortness_of_breath: sympt_covid_shortness_of_breath
      symptoms_since_last_visit_headache: sympt_covid_headache
      symptoms_since_last_visit_nausea_vomiting: sympt_covid_nausea_vomiting
      symptoms_since_last_visit_abdominal_pain: sympt_covid_abdominal_pain
      symptoms_since_last_visit_loss_of_appetite: sympt_covid_loss_of_appetite
      symptoms_since_last_visit_noisy_breathing_wheezing: sympt_covid_noisy_breathing
      symptoms_since_last_visit_runny_nose_sneezing: sympt_covid_runny_nose_sneezing
      symptoms_since_last_visit_more_trouble_sleeping: sympt_covid_trouble_sleeping
      symptoms_since_last_visit_diarrhoea: sympt_covid_diarrhoea
      symptoms_since_last_visit_loss_of_taste: sympt_covid_loss_of_taste
      symptoms_since_last_visit_loss_of_smell: sympt_covid_loss_of_smell
      symptoms_since_last_visit_memory_loss_or_confusion: sympt_covid_memoryloss_confused
      symptoms_since_last_visit_chest_pain: sympt_covid_chest_pain
      symptoms_since_last_visit_vertigo_dizziness: sympt_covid_vertigo_dizziness
      symptoms_since_last_visit_difficulty_concentrating: sympt_covid_difficult_concentra
      symptoms_since_last_visit_worry_anxiety: sympt_covid_worry_anxiety
      symptoms_since_last_visit_palpitations: sympt_covid_palpitations
      symptoms_since_last_visit_low_mood_or_not_enjoying_anything: sympt_covid_lowmood_notenjoying
      have_long_covid_symptoms: long_covid_have_symptoms
      long_covid_fever: long_covid_fever
      long_covid_weakness_tiredness: long_covid_weakness_tiredness
      long_covid_diarrhoea: long_covid_diarrhoea
      long_covid_loss_of_smell: long_covid_loss_of_smell
      long_covid_shortness_of_breath: long_covid_shortness_of_breath
      long_covid_vertigo_dizziness: long_covid_vertigo_dizziness
      long_covid_trouble_sleeping: long_covid_trouble_sleeping
      long_covid_headache: long_covid_headache
      long_covid_nausea_vomiting: long_covid_nausea_vomiting
      long_covid_loss_of_appetite: long_covid_loss_of_appetite
      long_covid_sore_throat: long_covid_sore_throat
      long_covid_chest_pain: long_covid_chest_pain
      long_covid_worry_anxiety: long_covid_worry_anxiety
      long_covid_memory_loss_or_confusion: long_covid_memory_loss_confusion
      long_covid_muscle_ache: long_covid_muscle_ache
      long_covid_abdominal_pain: long_covid_abdominal_pain
      long_covid_loss_of_taste: long_covid_loss_of_taste
      long_covid_cough: long_covid_cough
      long_covid_palpitations: long_covid_palpitations
      long_covid_low_mood: long_covid_low_mood_not_enjoying
      long_covid_difficulty_concentrating: long_covid_difficult_concentrate
      long_covid_runny_nose_sneezing: long_covid_runny_nose_sneezing
      long_covid_noisy_breathing: long_covid_noisy_breathing
      long_covid_reduce_activities: reduce_activities_long_covid
      is_regularly_lateral_flow_testing: covid_testing_regular
      other_pcr_test_since_last_visit: covid_test_swab
      other_pcr_test_results: covid_test_swab_result
      other_pcr_test_first_positive_date_string: covid_test_swab_pos_first_date
      other_pcr_test_last_negative_date_string: covid_test_swab_neg_last_date
      other_antibody_test_location: covid_test_blood_where
      other_antibody_test_since_last_visit: covid_test_blood
      other_antibody_test_results: covid_test_blood_result
      other_antibody_test_first_positive_date_string: covid_test_blood_pos_first_date
      other_antibody_test_last_negative_date_string: covid_test_blood_neg_last_date
      been_outside_uk_last_country: travel_abroad_country
      been_outside_uk_since_last_visit: travel_abroad
      been_outside_uk_last_date_string: travel_abroad_date
      is_self_isolating_detailed: self_isolating_v1
      is_self_isolating: self_isolating
      received_shielding_letter: received_shielding_letter
      contact_known_positive_covid_last_28_days: contact_known_covid
      last_covid_contact_location: contact_known_covid_type
      last_covid_contact_date_string: contact_known_covid_date
      contact_suspected_positive_covid_last_28_days: contact_suspect_covid
      last_suspected_covid_contact_location: contact_suspect_covid_type
      last_suspected_covid_contact_date_string: contact_suspect_covid_date
      hospital_last_28_days: contact_participant_hospital
      hospital_last_28_days_other_household_member: contact_other_in_hh_hospital
      household_been_hospital_last_28_days: contact_hospital
      care_home_last_28_days: contact_participant_carehome
      care_home_last_28_days_other_household_member: contact_other_in_hh_carehome
      household_been_care_home_last_28_days: contact_carehome
      physical_contact_under_18_years: contact_physical_18y
      physical_contact_18_to_69_years: contact_physical_18_69y
      physical_contact_over_70_years: contact_physical_70y
      social_distance_contact_under_18_years: contact_social_dist_18y
      social_distance_contact_18_to_69_years: contact_social_dist_18_to_69
      social_distance_contact_over_70_years: contact_social_dist_70y
      face_covering_outside_of_home: contact_face_covering
      face_covering_work: contact_face_covering_workschool
      face_covering_other_enclosed_places: contact_face_covering_other
      hours_a_day_with_someone_else_at_home: hours_someone_else_day
      times_hour_or_longer_another_home_last_7_days: others_home_hours
      times_hour_or_longer_another_person_your_home_last_7_days: others_own_home_hours
      times_outside_shopping_or_socialising_last_7_days: outside_shopping_times
      times_shopping_last_7_days: outside_shopping_only_times
      times_socialise_last_7_days: outside_socialising_only_times
      cis_covid_vaccine_offered: covid_vaccine_offered
      cis_covid_vaccine_type: covid_vaccine_type
      cis_covid_vaccine_type_other: covid_vaccine_type_other
      cis_covid_vaccine_number_of_doses: covid_vaccine_n_doses
      cis_covid_vaccine_received: covid_vaccine_havehad
      cis_covid_vaccine_date_string: covid_vaccine_date
      cis_flu_vaccine_received: flu_vaccine_havehad
      cis_covid_vaccine_date_1_string: covid_vaccine_date1
      cis_covid_vaccine_date_2_string: covid_vaccine_date2
      cis_covid_vaccine_date_3_string: covid_vaccine_date3
      cis_covid_vaccine_date_4_string: covid_vaccine_date4
      cis_covid_vaccine_type_1: covid_vaccine_type1
      cis_covid_vaccine_type_2: covid_vaccine_type2
      cis_covid_vaccine_type_3: covid_vaccine_type3
      cis_covid_vaccine_type_4: covid_vaccine_type4
      cis_covid_vaccine_type_other_1: covid_vaccine_type_other1
      cis_covid_vaccine_type_other_2: covid_vaccine_type_other2
      cis_covid_vaccine_type_other_3: covid_vaccine_type_other3
      cis_covid_vaccine_type_other_4: covid_vaccine_type_other4
