create_tables:
  - output_file_name: unioned_survey_responses
    table_name: valid_survey_responses
    column_name_map:
      ons_household_id: ons_household_id
      ordered_household_id: hh_id_fake
      hh_id: hh_id
      participant_id: participant_id
      survey_response_dataset_major_version: dataset
      consent_1_visit: consent_v1
      consent_5_visits: consent_v5
      consent_april_22: consent_to_april_22
      consent_16_visits: consent_v16
      consent_blood_test: consent_blood
      consent_contact_extra_research: consent_future_research
      consent_use_of_surplus_blood_samples: consent_blood_surplus
      consent_blood_samples_if_positive: consent_blood_if_positive
      consent_summary: consent
      consent_finger_prick_a1_a3: consent_to_finger_prick_a1_a3
      consent_extend_study_under_16_b1_b3: consent_to_extend_study_swab
      consent_contact_extra_research_yn: consent_future_researchYN
      consent_use_of_surplus_blood_samples_yn: consent_blood_surplusYN
      consent_blood_samples_if_positive_yn: consent_blood_if_positiveYN
      consent_fingerprick_blood_samples: consent_to_fingerprick_blood
      study_cohort: cohort
      visit_id: visit_id
      visit_datetime_string: visit_date_time
      visit_date_string: visit_date
      visit_date_type: visit_date_type
      visit_order: visit_order
      participant_visit_status: visit_status
      survey_response_type: visit_type
      samples_taken_datetime_string: samples_taken_date_time
      samples_taken_date_string: samples_taken_date
      swab_taken: swab_taken
      swab_sample_barcode_raw: swab_barcode_IQ
      swab_sample_barcode: swab_barcode_cleaned
      blood_taken: blood_taken
      blood_sample_barcode_raw: blood_barcode_IQ
      blood_sample_barcode: blood_barcode_cleaned
      sex: sex
      age_at_visit: age_at_visit
      ethnicity: ethnicity
      illness_reduces_activity_or_ability: health_conditions_impact
      illness_lasting_over_12_months: health_conditions
      ever_smoked_regularly: smoke_ever_regularly
      smoke_cigarettes: smoke_now_cigarettes
      smokes_cigar: smoke_now_cigar
      smokes_pipe: smoke_now_pipe
      smokes_vape_e_cigarettes: smoke_now_vape
      smokes_hookah_shisha_pipes: smoke_now_hookah_shisha
      smokes_nothing_now: smoke_now_nothing
      work_main_job_title: job_title
      work_main_job_role: main_resp
      work_sector_other: work_sector_other_text
      work_sector: work_sector
      work_health_care_area: work_healthcare_v1
      work_health_care_patient_facing: work_healthcare
      work_social_care: work_socialcare
      work_nursing_or_residential_care_home: work_care_nursing_home
      work_direct_contact_patients_or_clients: work_direct_contact_patients_etc
      work_status_v1_raw: orig_v1_work_status
      work_status_v2_raw: work_status_v2_orig
      work_status_v0: work_status
      work_status_v1: work_status_v1
      work_status_v2: work_status_v2
      work_location: work_location
      work_not_from_home_days_per_week: work_outside_home_days
      ability_to_socially_distance_at_work_or_education: work_social_distancing
      transport_to_work_or_education: work_travel
      think_have_covid_symptom_any: sympt_now_any
      think_have_covid_symptom_fever: sympt_now_fever
      think_have_covid_symptom_muscle_ache: sympt_now_muscle_ache_myalgia
      think_have_covid_symptom_fatigue: sympt_now_fatigue_weakness
      think_have_covid_symptom_sore_throat: sympt_now_sore_throat
      think_have_covid_symptom_cough: sympt_now_cough
      think_have_covid_symptom_shortness_of_breath: sympt_now_shortness_of_breath
      think_have_covid_symptom_headache: sympt_now_headache
      think_have_covid_symptom_nausea_or_vomiting: sympt_now_nausea_vomiting
      think_have_covid_symptom_abdominal_pain: sympt_now_abdominal_pain
      think_have_covid_symptom_diarrhoea: sympt_now_diarrhoea
      think_have_covid_symptom_loss_of_appetite: sympt_now_loss_of_appetite_or_e
      think_have_covid_symptom_more_trouble_sleeping: sympt_now_more_trouble_sleeping
      think_have_covid_symptom_noisy_breathing: sympt_now_noisy_breathing_wheez
      think_have_covid_symptom_runny_nose_or_sneezing: sympt_now_runny_nose_sneezing
      think_have_covid_symptom_loss_of_taste: sympt_now_loss_of_taste
      think_have_covid_symptom_loss_of_smell: sympt_now_loss_of_smell
      think_have_covid_symptom_vertigo_or_dizziness: sympt_now_vertigo_dizziness
      think_have_covid_symptom_difficulty_concentrating: sympt_now_difficulty_concentrate
      think_have_covid_symptom_palpitations: sympt_now_palpitations
      think_have_covid_symptom_memory_loss_or_confusion: sympt_now_memory_loss_confusion
      think_have_covid_symptom_chest_pain: sympt_now_chest_pain
      think_have_covid_symptom_anxiety: sympt_now_worry_anxiety
      think_have_covid_symptom_low_mood: sympt_now_low_mood_not_enjoying
      think_have_covid: think_have_covid_sympt_now
      think_have_covid_onset_date_string: sympt_now_date
      self_isolating_reason: self_isolating_v1
      self_isolating: self_isolating
      received_shielding_letter: received_shielding_letter
      contact_known_positive_covid_last_28_days: contact_known_covid
      last_covid_contact_type: contact_known_covid_type
      last_covid_contact_date_string: contact_known_covid_date
      contact_suspected_positive_covid_last_28_days: contact_suspect_covid
      last_suspected_covid_type: contact_suspect_covid_type
      last_suspected_covid_contact_date_string: contact_suspect_covid_date
      hospital_last_28_days: contact_participant_hospital
      other_household_member_hospital_last_28_days: contact_other_in_hh_hospital
      household_been_hospital_last_28_days: contact_hospital
      care_home_last_28_days: contact_participant_carehome
      other_household_member_care_home_last_28_days: contact_other_in_hh_carehome
      household_been_care_home_last_28_days: contact_carehome
      physical_contact_under_18_years: contact_physical_18y
      physical_contact_18_to_69_years: contact_physical_18_69y
      physical_contact_over_70_years: contact_physical_70y
      social_distance_contact_under_18_years: contact_social_dist_18y
      social_distance_contact_18_to_69_years: contact_social_dist_18_to_69
      social_distance_contact_over_70_years: contact_social_dist_70y
      face_covering_outside_of_home: contact_face_covering
      face_covering_work_or_education: contact_face_covering_workschool
      face_covering_other_enclosed_places: contact_face_covering_other
      think_had_covid: covid_think_havehad
      think_had_covid_onset_date_string: covid_date
      think_had_covid_contacted_nhs: covid_nhs_contact
      think_had_covid_admitted_to_hospital: covid_admitted
      think_had_covid_any_symptoms: sympt_covid_any
      think_had_covid_symptom_fever: sympt_covid_fever
      think_had_covid_symptom_muscle_ache: sympt_covid_muscle_ache_myalgia
      think_had_covid_symptom_fatigue: sympt_covid_fatigue_weakness
      think_had_covid_symptom_sore_throat: sympt_covid_sore_throat
      think_had_covid_symptom_cough: sympt_covid_cough
      think_had_covid_symptom_shortness_of_breath: sympt_covid_shortness_of_breath
      think_had_covid_symptom_headache: sympt_covid_headache
      think_had_covid_symptom_nausea_or_vomiting: sympt_covid_nausea_vomiting
      think_had_covid_symptom_abdominal_pain: sympt_covid_abdominal_pain
      think_had_covid_symptom_loss_of_appetite: sympt_covid_loss_of_appetite
      think_had_covid_symptom_noisy_breathing: sympt_covid_noisy_breathing
      think_had_covid_symptom_runny_nose_or_sneezing: sympt_covid_runny_nose_sneezing
      think_had_covid_symptom_more_trouble_sleeping: sympt_covid_trouble_sleeping
      think_had_covid_symptom_diarrhoea: sympt_covid_diarrhoea
      think_had_covid_symptom_loss_of_taste: sympt_covid_loss_of_taste
      think_had_covid_symptom_loss_of_smell: sympt_covid_loss_of_smell
      think_had_covid_symptom_memory_loss_or_confusion: sympt_covid_memoryloss_confused
      think_had_covid_symptom_chest_pain: sympt_covid_chest_pain
      think_had_covid_symptom_vertigo_or_dizziness: sympt_covid_vertigo_dizziness
      think_had_covid_symptom_difficulty_concentrating: sympt_covid_difficult_concentra
      think_had_covid_symptom_anxiety: sympt_covid_worry_anxiety
      think_had_covid_symptom_palpitations: sympt_covid_palpitations
      think_had_covid_symptom_low_mood: sympt_covid_lowmood_notenjoying
      other_covid_infection_test: covid_test_swab
      other_covid_infection_test_results: covid_test_swab_result
      other_covid_infection_test_first_positive_date_string: covid_test_swab_pos_first_date
      other_covid_infection_test_last_negative_date_string: covid_test_swab_neg_last_date
      other_antibody_test_location: covid_test_blood_where
      other_antibody_test: covid_test_blood
      other_antibody_test_results: covid_test_blood_result
      other_antibody_test_first_positive_date_string: covid_test_blood_pos_first_date
      other_antibody_test_last_negative_date_string: covid_test_blood_neg_last_date
      been_outside_uk_last_country: travel_abroad_country
      been_outside_uk: travel_abroad
      been_outside_uk_last_return_date: travel_abroad_date
      think_have_long_covid: long_covid_have_symptoms
      think_have_long_covid_symptom_fever: long_covid_fever
      think_have_long_covid_symptom_fatigue: long_covid_weakness_tiredness
      think_have_long_covid_symptom_diarrhoea: long_covid_diarrhoea
      think_have_long_covid_symptom_loss_of_smell: long_covid_loss_of_smell
      think_have_long_covid_symptom_shortness_of_breath: long_covid_shortness_of_breath
      think_have_long_covid_symptom_vertigo_or_dizziness: long_covid_vertigo_dizziness
      think_have_long_covid_symptom_more_trouble_sleeping: long_covid_trouble_sleeping
      think_have_long_covid_symptom_headache: long_covid_headache
      think_have_long_covid_symptom_nausea_or_vomiting: long_covid_nausea_vomiting
      think_have_long_covid_symptom_loss_of_appetite: long_covid_loss_of_appetite
      think_have_long_covid_symptom_sore_throat: long_covid_sore_throat
      think_have_long_covid_symptom_chest_pain: long_covid_chest_pain
      think_have_long_covid_symptom_anxiety: long_covid_worry_anxiety
      think_have_long_covid_symptom_memory_loss_or_confusion: long_covid_memory_loss_confusion
      think_have_long_covid_symptom_muscle_ache: long_covid_muscle_ache
      think_have_long_covid_symptom_abdominal_pain: long_covid_abdominal_pain
      think_have_long_covid_symptom_loss_of_taste: long_covid_loss_of_taste
      think_have_long_covid_symptom_cough: long_covid_cough
      think_have_long_covid_symptom_palpitations: long_covid_palpitations
      think_have_long_covid_symptom_low_mood: long_covid_low_mood_not_enjoying
      think_have_long_covid_symptom_difficulty_concentrating: long_covid_difficult_concentrate
      think_have_long_covid_symptom_runny_nose_or_sneezing: long_covid_runny_nose_sneezing
      think_have_long_covid_symptom_noisy_breathing: long_covid_noisy_breathing
      think_have_long_covid_symptom_reduced_ability: reduce_activities_long_covid
      outward_postcode: outer_postcode
      approached_for_blood_samples: approached_for_blood_samples
      hours_a_day_with_someone_else_at_home: hours_someone_else_day
      reconsented_blood: re_consent_blood
      times_hour_or_longer_another_home_last_7_days: others_home_hours
      times_hour_or_longer_another_person_your_home_last_7_days: others_own_home_hours
      times_outside_shopping_or_socialising_last_7_days: outside_shopping_times
      times_shopping_last_7_days: outside_shopping_only_times
      times_socialising_last_7_days: outside_socialising_only_times
      confirm_received_vouchers: confirm_received_vouchers
      have_landline_number: have_landline_number
      have_mobile_number: have_mobile_number
      cis_covid_vaccine_type_other: covid_vaccine_type_other
      participant_testing_group: work_type
      household_fingerprick_status: fingerprick_status_hh
      able_to_take_blood: able_to_take_blood
      no_fingerprick_blood_taken_reason: no_blood_reason_fingerprick
      no_venous_blood_taken_reason: no_blood_reason_venous
      accepted_fingerprick_invite: accepted_fingerprick_invite
      cis_covid_vaccine_offered: covid_vaccine_offered
      regularly_lateral_flow_testing: covid_testing_regular
      swab_sample_barcode_edited_flag: flag_barcode_swab
      blood_sample_barcode_edited_flag: flag_barcode_blood
      household_visit_status: appointment_status
      participant_survey_status: withdrawn_participant
      participant_withdrawal_reason: reason_for_withdrawal
      cis_covid_vaccine_type: covid_vaccine_type
      cis_covid_vaccine_number_of_doses: covid_vaccine_n_doses
      work_main_job_changed: main_job_changed
      work_in_additional_paid_employment: additional_paid_employment
      cis_covid_vaccine_received: covid_vaccine_havehad
      cis_covid_vaccine_date_string: covid_vaccine_date
      participant_withdrawal_reason_raw: withdrawal_reason
      date_of_birth_string: dob
      cis_flu_vaccine_received: flu_vaccine_havehad
      deferred: deferred
      improved_visit_date_string: actual_visit_date
      not_attended_reason: not_attend_reason
      cis_covid_vaccine_date_1_string: covid_vaccine_date1
      cis_covid_vaccine_date_2_string: covid_vaccine_date2
      cis_covid_vaccine_date_3_string: covid_vaccine_date3
      cis_covid_vaccine_date_4_string: covid_vaccine_date4
      cis_covid_vaccine_type_1: covid_vaccine_type1
      cis_covid_vaccine_type_2: covid_vaccine_type2
      cis_covid_vaccine_type_3: covid_vaccine_type3
      cis_covid_vaccine_type_4: covid_vaccine_type4
      cis_covid_vaccine_type_other_1: covid_vaccine_type_other1
      cis_covid_vaccine_type_other_2: covid_vaccine_type_other2
      cis_covid_vaccine_type_other_3: covid_vaccine_type_other3
      cis_covid_vaccine_type_other_4: covid_vaccine_type_other4
      participant_withdrawal_type: withdrawn_type
      people_in_household_count: n_participants_corrected
