stages:
  - function: bloods_delta_ETL
    run: True
    resource_path: "hdfs:///ons/covserolink/landing_zone/bloods/Unioxf_medtestN_20210929.csv"

  - function: swab_delta_ETL
    run: True
    resource_path: "hdfs:///ons/covserolink/landing_zone/swabs/ONS_GL_Report_20210926_0000.csv"

  - function: survey_responses_version_2_ETL
    run: True
    resource_path: "hdfs:///ons/covserolink/landing_zone/responses_v2/ONSECRF5_Datafile_20210929.csv"

  - function: process_post_merge
    run: False

  - function: merge_antibody_etl
    run: True

  - function: merge_swab_etl
    run: True


storage:
  database: covserolink_dev
  table_prefix: fosted1_
  write_mode: append

csv_output_path: "/home/cdsw/output"
