exclusion_files:
  survey_responses: [

  ]
  blood: [

  ]
  swab: [

  ]


stages:
  - function: delete_tables
    run: False
    prefix: USER_
    table_names:
    pattern:

  - function: historical_blood_ETL
    run: False
    resource_path: "hdfs:///ons/covserolink/landing_zone/historical_bloods/historical_bloods_*.csv"
    include_invalid: True
    include_processed: True

  - function: blood_delta_ETL
    run: False
    resource_path: "hdfs:///ons/covserolink/landing_zone/bloods/Unioxf_medtest*.csv"
    include_invalid: True
    include_processed: True

  - function: swab_delta_ETL
    run: False
    resource_path: "hdfs:///ons/covserolink/landing_zone/swabs/ONS_GL_Report_*.csv"
    include_invalid: True
    include_processed: True

  - function: survey_responses_version_0_ETL
    run: False
    resource_path: "hdfs:///ons/covserolink/landing_zone/responses_v0/ONS_Datafile_*.csv"
    latest_only: True
    include_invalid: True
    include_processed: True
    end_date: 2028-12-31

  - function: survey_responses_version_1_ETL
    run: False
    resource_path: "hdfs:///ons/covserolink/landing_zone/responses_v1/ONSECRF4_Datafile_*.csv"
    latest_only: True
    include_invalid: True
    include_processed: True
    end_date: 2028-12-31

  - function: survey_responses_version_2_ETL
    run: False
    resource_path: "hdfs:///ons/covserolink/landing_zone/responses_v2/ONSECRF5_Datafile_*.csv"
    latest_only: True
    include_invalid: True
    include_processed: True
    end_date: 2028-12-31

  - function: union_survey_response_files
    run: False
    unioned_survey_table: unioned_survey_responses
    transformed_survey_table: transformed_survey_responses_v*_data

  - function: union_dependent_transformations
    run: False
    unioned_survey_table: unioned_survey_responses
    transformed_table: post_union_transformed_survey_responses

  - function: validate_survey_responses
    run: True
    unioned_survey_table: unioned_survey_responses
    valid_survey_table: validated_survey_responses
    invalid_survey_table: erroneous_survey_responses

  - function: outer_join_blood_results
    run: False
    blood_table: transformed_blood_test_data
    antibody_table: joined_blood_test_data
    failed_blood: failed_blood_test_join


  - function: merge_blood_ETL
    run: False
    antibody_table: joined_blood_test_data
    unioned_survey_table: post_union_transformed_survey_responses
    antibody_output_tables: [
      "merged_responses_antibody_data",
      "antibody_merge_residuals",
      "antibody_merge_failed_records",
    ]


  - function: merge_swab_ETL
    run: False
    swab_table: transformed_swab_test_data
    unioned_survey_table: merged_responses_antibody_data
    swab_output_tables: [
      "merged_responses_antibody_swab_data",
      "swab_merge_residuals",
      "swab_merge_failed_records",
    ]

  - funciton: join_vaccination_data
    run: False
    nims_table:
    participant_records_table: participant_level_key_records
    vaccination_data_table: participant_level_with_vaccination_data


  - function: process_post_merge
    run: False
    merged_antibody_swab_table: merged_responses_antibody_swab_data
    imputed_values_table: imputed_value_lookup
    participant_records_table: participant_level_key_records
    response_records_table: response_level_records
    invalid_response_records_table: invalid_response_records_future

  - function: record_level_interface
    run: False
    input_table:
    csv_editing_file:
    unique_id_column:
    unique_id_list: []

  - function: sample_file_ETL
    run: False
    address_lookup: "hdfs:///ons/covserolink/landing_zone/weights_input/Address_lookup.csv"
    cis_lookup: "hdfs:///ons/covserolink/landing_zone/weights_input/cis_lookup.csv"
    country_lookup: "hdfs:///ons/covserolink/landing_zone/weights_input/country_lookup.csv"
    postcode_lookup: "hdfs:///ons/covserolink/landing_zone/weights_input/lookup.csv"
    new_sample_file: "hdfs:///ons/covserolink/landing_zone/weights_input/new_sample_file.csv"
    tranche: "hdfs:///ons/covserolink/landing_zone/weights_input/tranche.csv"
    table_or_path: path
    old_sample_file: "hdfs:///ons/covserolink/landing_zone/weights_input/old_sample_file.csv"
    design_weight_table: participant_geographies_design_weights

  - function: population_projection
    run: False
    population_projection_previous: "hdfs:///ons/covserolink/landing_zone/weights_input/population_projection_p.csv"
    population_projection_current: "hdfs:///ons/covserolink/landing_zone/weights_input/population_projection_c.csv"
    tranche: "hdfs:///ons/covserolink/landing_zone/weights_input/tranche.csv"
    month: 1
    aps_lookup: "hdfs:///ons/covserolink/landing_zone/weights_input/aps_lookup.csv"
    table_or_path: path
    population_totals_table: population_totals_for_calibration
    population_projections_table: population_projections

  - function: pre_calibration
    run: False
    design_weight_table: participant_geographies_design_weights
    survey_response_table: merged_responses_antibody_swab_data
    population_projections_table: population_projections
    responses_pre_calibration_table: responses_pre_calibration
    pre_calibration_config_path: /home/cdsw/precal_config.yaml


  - function: weight_calibration
    run: False
    population_totals_table: population_totals_for_calibration
    responses_pre_calibration_table: responses_pre_calibration
    base_output_table_name: calibrated_weights
    calibration_config_path: /home/cdsw/calibration_config.yaml

  - function: sample_file_ETL
    run: False
    address_lookup: "hdfs:///ons/covserolink/landing_zone/weights_input/Address_lookup.csv"
    cis_lookup: "hdfs:///ons/covserolink/landing_zone/weights_input/cis_lookup.csv"
    country_lookup: "hdfs:///ons/covserolink/landing_zone/weights_input/country_lookup.csv"
    postcode_lookup: "hdfs:///ons/covserolink/landing_zone/weights_input/lookup.csv"
    new_sample_file: "hdfs:///ons/covserolink/landing_zone/weights_input/new_sample_file.csv"
    tranche: "hdfs:///ons/covserolink/landing_zone/weights_input/tranche.csv"
    table_or_path: path
    old_sample_file: "hdfs:///ons/covserolink/landing_zone/weights_input/old_sample_file.csv"
    design_weight_table: participant_geographies_design_weights

  - function: population_projection
    run: False
    population_projection_previous: "hdfs:///ons/covserolink/landing_zone/weights_input/population_projection_p.csv"
    population_projection_current: "hdfs:///ons/covserolink/landing_zone/weights_input/population_projection_c.csv"
    tranche: "hdfs:///ons/covserolink/landing_zone/weights_input/tranche.csv"
    month: 1
    aps_lookup: "hdfs:///ons/covserolink/landing_zone/weights_input/aps_lookup.csv"
    table_or_path: path
    population_totals_table: population_totals_for_calibration
    population_projections_table: population_projections

  - function: pre_calibration
    run: False
    design_weight_table: participant_geographies_design_weights
    survey_response_table: merged_responses_antibody_swab_data
    population_projections_table: population_projections
    responses_pre_calibration_table: responses_pre_calibration
    pre_calibration_config_path: /home/cdsw/precal_config.yaml


  - function: weight_calibration
    run: False
    population_totals_table: population_totals_for_calibration
    responses_pre_calibration_table: responses_pre_calibration
    base_output_table_name: calibrated_weights
    calibration_config_path: /home/cdsw/calibration_config.yaml

  - function: generate_outputs
    run: False

  - function: tables_to_csv
    run: True
    update_name_map: unioned_responses_update_map
    category_map: iqvia_raw_category_map
    table_file_pairs:
        - [unioned_survey_responses, unioned_survey_responses]
    outgoing_directory: hdfs:///ons/covserolink/output_data

storage:
    database: covserolink_dev
    table_prefix: USER_
    write_mode: append

pyspark_session_size: l
