# This is a basic workflow that is manually triggered

name: bump_UAT_version

# Test to bumpversion of code
on:
  schedule:
  - cron: '0 9 * * 0'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.8
      uses: actions/setup-python@v2
      with:
          python-version: 3.6.8
    - name: Test cron bumpversion
      run: |
        echo "This is a test!!"
        pip3 install bump2version
        bumpversion --verbose pre 
        git push
        git push --tags
        
        
        
        
