on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_docs:
    concurrency: ci-${{ github.ref }}
    name: Build and deploy docs to Pages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install --upgrade-strategy eager -e .[ci]
    - name: Build the book
      run: |
        (cd docs && make html)
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: docs/build
