# This is a basic workflow to help you get started with Actions

name: Testing and coverage

# Controls when the action will run.
on:
  # Triggers the workflow on push events for the main branch
  push:
    branches: [ main ]
  pull_request: # And on all Pull Requests

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.8

      - name: Check package build
        run: |
          python -m pip install --upgrade pip
          pip install wheel==0.29.0
          python setup.py sdist bdist_wheel
  test-with-cov:
    runs-on: ubuntu-16.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Set up Python 3.6.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.8

      - name: Install Python dependencies
        # Wheel is specific here because of conflicts on this Python version
        run: |
          python -m pip install --upgrade pip
          pip install pypandoc==1.5
          pip install -e .[ci]
      - name: Run pytest
        run: |
          pytest -v
      - name: Run pytest with coverage
        run: |
          pytest --cov=cishouseholds --cov-report=xml --cov-report=term-missing
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: cishouseholds-pytests-py3.6.8
          flags: pytests
          file: ./coverage.xml
          fail_ci_if_error: true
